### PR TITLE
Converted to Maven, updated dependencies, removed warnings

### PR DESCRIPTION
**Pull request by DalekCraft2**
Note that I do not really know what to do to make it Mac-compatible because I do not own a Mac. I have not really done anything with the .zip folder. I tested the code by just running the Main file in IntelliJ instead of using the batch and command files.

To make it work better, I would need to learn how to use Swing. Maybe I should do that.

### CODE REVIEW

**Comment by eccentricdevotion** [comment]
TARDISSchematicViewer is obsolete and will no longer work with the current .tschm format...

**Comment by DalekCraft2** [comment]
Could it be made to work with the modern format by using the schematic-copying/pasting code from the main plugin?

**Comment by eccentricdevotion** [comment]
Thinking of archiving this as I don't think anybody actually uses it (or knows of its existence) and it needs updating to post-1.13 Minecraft/Spigot and I don't really have the time or inclination...

**Comment by DalekCraft2** [comment]
Does TARDIS even have a reason for using a proprietary schematic format? Using a standard would be simpler. The TARDIS plugin seems to try to bundle a bunch of features, like schematic creation, which is a bit unnecessary, because they are all features in plugins which almost everyone uses.

**Comment by eccentricdevotion** [comment]
TARDIS uses its own schematic format for a number of reasons, but mostly because:

1. You should be able to use the plugin without installing anything else but TCG.
2. When Minecraft changes majorly i.e from 1.12 - 1.13, things break. Other plugins, in this case WorldEdit took a long time to update their schematic format. TARDIS was updated rapidly as it didn't rely on another format. This is why TARDIS also has it's own world management (why not use Multiverse?), custom dimensions (all other custom terrain plugins are either obsolete or premium plugins), tp/weather/gm commands etc (why not use essentials?) all because I can't be bothered to wait for them to update...
3. I code plugins to extend myself, not really to play Minecraft as such, adding features like this lets me learn new things.

**Comment by DalekCraft2** [comment]
Had an idea: Perhaps the features which are commonly replicated by other plugins (minus the proprietary schematic creation) could be separated into some sort of utility addon so the plugin is less cluttered.

**Pull request closed without merging**
